[package]
name = "call_api"
version = "0.1.0"
edition = "2024"
authors = ["Stuart Thompson"]
description = "A sample API client"

[dependencies]
axum = { version = "0.8.4" }
dotenv = "0.15.0"
serde = "1.0.219"
