[package]
name = "chat"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1"
tokio = { version ="1", features = ["sync"] }
serde = { version = "1", features = ["rc", "derive"] }
serde_json = "1"
