[package]
name = "lang_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1"
num = "0.4"
regex = "1"
text-colorizer = "1"
macros = { path = "../macros" }
async-std = "1"
disjoint-sets = "0.4.2"
